/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MountingImport } from './routes/mounting'
import { Route as EnhancedSwitchImport } from './routes/enhanced-switch'
import { Route as DraggableMotionImport } from './routes/draggable-motion'
import { Route as BasicAnimationImport } from './routes/basic-animation'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MountingRoute = MountingImport.update({
  path: '/mounting',
  getParentRoute: () => rootRoute,
} as any)

const EnhancedSwitchRoute = EnhancedSwitchImport.update({
  path: '/enhanced-switch',
  getParentRoute: () => rootRoute,
} as any)

const DraggableMotionRoute = DraggableMotionImport.update({
  path: '/draggable-motion',
  getParentRoute: () => rootRoute,
} as any)

const BasicAnimationRoute = BasicAnimationImport.update({
  path: '/basic-animation',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/basic-animation': {
      preLoaderRoute: typeof BasicAnimationImport
      parentRoute: typeof rootRoute
    }
    '/draggable-motion': {
      preLoaderRoute: typeof DraggableMotionImport
      parentRoute: typeof rootRoute
    }
    '/enhanced-switch': {
      preLoaderRoute: typeof EnhancedSwitchImport
      parentRoute: typeof rootRoute
    }
    '/mounting': {
      preLoaderRoute: typeof MountingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  BasicAnimationRoute,
  DraggableMotionRoute,
  EnhancedSwitchRoute,
  MountingRoute,
])

/* prettier-ignore-end */
